# Generated by Django 3.0 on 2020-09-21 19:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_autor_categoria_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroHabilitado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('nro_tel', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('ciudad', models.CharField(blank=True, default='Resistencia', max_length=50, null=True)),
                ('horario_aten', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'CentroHabilitado',
                'verbose_name_plural': 'CentrosHabilitados',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Autor')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
