# Generated by Django 3.0 on 2020-09-21 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_centrohabilitado_comentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CentroHabilitado',
        ),
    ]
