# Generated by Django 3.0 on 2020-09-29 15:21

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('centros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnableCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mail', models.CharField(max_length=200)),
                ('phone_num', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('business_hours', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='CentroHabilitado',
        ),
    ]
