# Generated by Django 3.0 on 2020-09-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha nacimiento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Apellidos'),
        ),
    ]
