# Generated by Django 3.0 on 2020-09-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200929_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_donante',
            field=models.BooleanField(default=False, verbose_name='Donante/Futuro donante'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='factor_rh',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Factor Rh'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Grupo'),
        ),
    ]
