# Generated by Django 3.0 on 2020-09-21 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200919_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centrohabilitado',
            name='long_lat',
        ),
    ]
