# Generated by Django 3.0 on 2020-09-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200921_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True),
        ),
    ]
